### ISSUE TITLE
AttributeError: 'tuple' object has no attribute 'permute'

### ISSUE THREAD

**Issue by librlike** [Cram3r95/mapfe4mp#3]
May I use train again_ Gan_ Social_ LSTM_ The following errors occurred during the training of the MHSA model：
Traceback (most recent call last):
  File "/mnt/f/pycharm-professional/pytorch-project/VectorNet-GAN/mapfe4mp-master/train.py", line 143, in <module>
    model_trainer(config, logger)
  File "/mnt/f/pycharm-professional/pytorch-project/VectorNet-GAN/mapfe4mp-master/model/trainers/other/trainer_gan_social_lstm_mhsa.py", line 271, in model_trainer
    losses_d = discriminator_step(hyperparameters, batch, generator,
  File "/mnt/f/pycharm-professional/pytorch-project/VectorNet-GAN/mapfe4mp-master/model/trainers/other/trainer_gan_social_lstm_mhsa.py", line 489, in discriminator_step
    pred_traj_fake = relative_to_abs(pred_traj_fake_rel, obs_traj[-1])
  File "/mnt/f/pycharm-professional/pytorch-project/VectorNet-GAN/mapfe4mp-master/model/datasets/argoverse/dataset_utils.py", line 394, in relative_to_abs
    rel_traj = rel_traj.permute(1, 0, 2)
AttributeError: 'tuple' object has no attribute 'permute'
Excuse me, class TrajectoryGenerator (nn. Module): Is this part of the code correct and why is it returning pre d_ Traj_ Fake_ Rel returns a tuple, but tuples cannot use relative_ To_ ABS function

**Comment by Cram3r95** [comment]
Hi. I am modifying the repo to have a stable version. Thank you!
